server:
  port: 8080

spring:
  application:
    name: customer
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: 'true'
        temp:
          se_jdbc_metadata_defaults: 'false'
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer
    username: 'amigoscode'
    password: 'password'
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
zipkin:
  base-url: http://localhost:9411
  sleuth:
    sampler:
      # 採樣率，模式0.1，也就是10%，為了便於觀察效果，改為1.0，也就是100%。生產環境建議保持默認。
      probability: 1.0